### ISSUE TITLE
help wanted: Can I access the kusto cluster data with a user account rather than a authorized client(app) by Go SDK

### ISSUE THREAD

**Issue by PenguinCats** [Azure/azure-kusto-go#101]
This is an ask for help, Thanks.

The Go SDK autorest.Authorizer is commonly initialized with ClientID, TenantID, which means I need to create an app and authorize it to access kusto cluster.  Besides, I guess Kusto itself is an application(Client) ?
However, I hope to access the kusto cluster directly with an authorized user account.  I have check https://docs.microsoft.com/zh-cn/azure/data-explorer/kusto/management/access-control/how-to-authenticate-with-aad but fail to find a solution. Could you give me a more detaied infomation?

Thanks a lot.

**Comment by yogilad** [comment]
Hi,

We currently support any auth method provided by https://github.com/Azure/go-autorest/blob/main/autorest/azure/auth/auth.go

There's device code auth and user/password auth you can attempt to use (the latter is less recommended).
