### ISSUE TITLE
Error unwrapping is not occurring correctly on queries that end due to a return limit

### ISSUE THREAD

**Issue by element-of-surprise** [Azure/azure-kusto-go#108]
By default Kusto queries are limited to some number of return values (I don't remember what the value is).

So if you use the SDK to make a query and you reach that threshold, you will receive:

```
(panic: json: cannot unmarshal object into Go struct field DataSetCompletion.OneApiErrors of type string)
```

This means the error message being returned by Kusto cannot be converted from its JSON representation to whatever error format we have.

This is probably related to:
https://github.com/Azure/azure-kusto-go/issues/12

I remember that being a mess I wanted to correct, but don't remember all the details and haven't gone back over it.  

But this should be returning that limit error instead of this internal JSON decode error about decoding an error.

**Comment by AsafMah** [comment]
This might be the same as #124

john, can you run it again and see what json it fails to parse exactly? (we now print out the failed json)

**Comment by AsafMah** [comment]
Any updates?
