### ISSUE TITLE
Doesn't support Azure sovereign cloud 

### ISSUE THREAD

**Issue by zetiaatgithub** [Azure/azure-kusto-go#113]
When ingesting logs to kusto in usgovvirginia region, I got the following error. 
`ingest.New client failed with error: problem reading ingestion resources from Kusto: the StorageRoot URI received(https://***.blob.core.usgovcloudapi.net/2022*******0Z&sp=rw) has an error: URI hostname does not end with '.core.windows.net'`

Could we add interface for adding trusted endpoints? Just like in this doc:  https://docs.microsoft.com/en-us/azure/data-explorer/kusto/api/connection-strings/kusto#trusted-endpoints

**Comment by yogilad** [comment]
You are right, this validation is not cloud agnostic.
labeled as bug for fixing

**Comment by AsafMah** [comment]
Fixed in 0.10.1
