### ISSUE TITLE
.show database Samples schema returns err "column of type System.String, which was unknown"

### ISSUE THREAD

**Issue by jesseward** [Azure/azure-kusto-go#116]
Running the `Mgmt(..)` query `.show database Samples schema` returns the error `DataTable had column of type System.String, which was unknown`. 

I am seeing this error on a number of databases I have been developing against and tests against the Samples demonstration database also return this error.

The following code can reproduce.

```go
package main

import (
	"context"
	"fmt"
	"io"
	"os"

	"github.com/Azure/azure-kusto-go/kusto"
	"github.com/Azure/go-autorest/autorest/azure/auth"
)

const (
	showTablesKql    = ".show tables | project TableName" // good query..
	showDbKql        = ".show database Samples schema"    // bad query
	dbName           = "Samples"                          // via https://help.kusto.windows.net
	connectionString = "https://help.kusto.windows.net"
)

func check(err error, where string) {
	if err != nil {
		fmt.Fprintf(os.Stderr, "ERROR: %s -> %v\n", where, err)
		os.Exit(1)
	}
}

func main() {
	azCreds, err := auth.NewAuthorizerFromCLIWithResource(connectionString)
	check(err, "authorizer")

	authorizer := kusto.Authorization{Authorizer: azCreds}
	client, err := kusto.New(connectionString, authorizer)
	check(err, "client")

	rows, err := client.Mgmt(context.Background(), dbName, kusto.NewStmt(showDbKql))
	check(err, "mgmt")

	for {
		row, err := rows.Next()
		if err != nil {
			if err == io.EOF {
				check(err, "eof")
			}
			check(err, "row")
		}
		fmt.Printf("%#v\n", row)
	}
}

```

Running the above returns
```sh
go run main.go 
ERROR: row -> DataTable had column of type System.String, which was unknown
exit status 1
```

Note that if you swap to another working query (eg `showTablesKql`), it confirms parsing of other mgmt commands are successful.

**Comment by element-of-surprise** [comment]
At a quick glance, I'd guess something is causing this line to occur:
***@***.***/-/blob/kusto/internal/frames/v1/v1.go?L41


Which is in turn skipping the V1 frames type translation from happening on line:
https://sourcegraph.com/github.com/Azure/azure-kusto-go/-/blob/kusto/internal/frames/v1/v1.go?L47

V1 and V2 frames have different names for types and we have an internal type in Go we use to represent all column types.  Normally, what should happen, is when we receive a V1 frame and we translate it to the correct type. In this case:
"system.string":                   types.String

That looks like it is getting skipped.


John Doak
Manager, Layer 1 Reliability Engineering
***@***.***
________________________________
From: Jesse Ward ***@***.***>
Sent: Tuesday, September 20, 2022 2:26 PM
To: Azure/azure-kusto-go ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [Azure/azure-kusto-go] .show database Samples schema returns err "column of type System.String, which was unknown" (Issue #116)


Running the Mgmt(..) query .show database Samples schema returns the error DataTable had column of type System.String, which was unknown.

I am seeing this error on a number of databases I have been developing against and tests against the Samples demonstration database also return this error.

The following code can reproduce.

package main

import (
        "context"
        "fmt"
        "io"
        "os"

        "github.com/Azure/azure-kusto-go/kusto"
        "github.com/Azure/go-autorest/autorest/azure/auth"
)

const (
        showTablesKql    = ".show tables | project TableName" // good query..
        showDbKql        = ".show database Samples schema"    // bad query
        dbName           = "Samples"                          // via https://help.kusto.windows.net
        connectionString = "https://help.kusto.windows.net"
)

func check(err error, where string) {
        if err != nil {
                fmt.Fprintf(os.Stderr, "ERROR: %s -> %v\n", where, err)
                os.Exit(1)
        }
}

func main() {
        azCreds, err := auth.NewAuthorizerFromCLIWithResource(connectionString)
        check(err, "authorizer")

        authorizer := kusto.Authorization{Authorizer: azCreds}
        client, err := kusto.New(connectionString, authorizer)
        check(err, "client")

        rows, err := client.Mgmt(context.Background(), dbName, kusto.NewStmt(showDbKql))
        check(err, "mgmt")

        for {
                row, err := rows.Next()
                if err != nil {
                        if err == io.EOF {
                                check(err, "eof")
                        }
                        check(err, "row")
                }
                fmt.Printf("%#v\n", row)
        }
}

Running the above returns

go run main.go
ERROR: row -> DataTable had column of type System.String, which was unknown
exit status 1

Note that if you swap to another working query (eg showTablesKql), it confirms parsing of other mgmt commands are successful.
