### ISSUE TITLE
cannot use time.Now() as parameters' default value;

### ISSUE THREAD

**Issue by 1730735794** [Azure/azure-kusto-go#118]
Description
cannot use time.Now() as parameters' default value;
such as

     timeFilter, err := kusto.NewDefinitions().With(
		kusto.ParamTypes{
			"beginTime": kusto.ParamType{Type: types.DateTime, Default: time.Now()},
			"endTime":   kusto.ParamType{Type: types.DateTime, Default: time.Now()},
			"name":      kusto.ParamType{Type: types.String, Default: ""},
			"mess":      kusto.ParamType{Type: types.String, Default: ""},
		},
	)
it can be send to kusto, but will get a 400 bad request.

"@message": "Syntax error: SYN0002: A recognition error occurred. [line:position=1:50]",

Affected Modules, Packages, Versions and Symbols

Module: github.com/example/module
Package: github.com/example/module/package
Versions:
  - Introduced: 1.2.0
  - Fixed: 1.2.4
Symbols:
  - aFunction
  - SomeType.AMethod

Module: github.com/example/module/v2
Package: github.com/example/module/v2/package
Versions:
  - Fixed: 2.4.5
Symbols:
  - anotherFunction

**Comment by AsafMah** [comment]
Version 0.9.2 Fixes it, please let us know if there are further issues.
