### ISSUE TITLE
ingest.IngestionMappingRef should define the default data type

### ISSUE THREAD

**Issue by 0xThiebaut** [Azure/azure-kusto-go#119]
When ingesting data using the `ingest.IngestionMappingRef` option, the mapping's data type should be used as default data type instead of `CSV`.

As an example, relying on the `ingest.IngestionMappingRef("ExampleMapping", ingest.JSON)` option should change the default data type from `CSV` to `JSON`, resulting in the `ingest.IngestionMappingRef` not relying on another `ingest.FileFormat` option.

It felt counter-intuitive to specify the format twice.

**Comment by AsafMah** [comment]
Fixed in 0.9.1, if you have further issues please re-open.
