### ISSUE TITLE
DoOnRowOrError() returns "json: cannot unmarshal object into Go struct field DataSetCompletion.OneApiErrors of type string"

### ISSUE THREAD

**Issue by liranms** [Azure/azure-kusto-go#124]
The function DoOnRowOrError(f) returns an error "json: cannot unmarshal object into Go struct field DataSetCompletion.OneApiErrors of type string"
this happens intermittently, most likely when there is a kusto server side error
My callback (the parameter f) never returns an error there, I don't have the raw response but if I had to guess I would assume that the server does not return a []string (the type of OneApiErrors) but a single string instead.

**Comment by AsafMah** [comment]
I couldn't recreate the error, but version 0.9.1 should also print the raw json. Can you upgrade and see what you get?

**Comment by AsafMah** [comment]
@liranms have you retried?

**Comment by yogilad** [comment]
@liranms , closing this.
If you have new information or repro steps, feel free to reopen.
