### ISSUE TITLE
Unable to parse responses where "IsProgressive":false though includes progressive tables

### ISSUE THREAD

**Issue by jesseward** [Azure/azure-kusto-go#125]
## Summary

Recently (`2022-10-24`) queries to our Kusto cluster have stopped parsings result into the `kusto.RowIterator` object. Sending the same query using the `QueryToJson(..)` function does assert that the appropriate rows are being returned from the API. Which hints that this is a parsing problem within the `azure-kusto-go` library. Tests using these same DB+query using the `azure-kusto-python` library, were successful as well. So the Python lib could handle the oddity that our server is returning.

**Note** I have full request/response payload available and can share over our common MS Teams channel (I am a GitHub employee). Feel free to connect over Teams if you'd like to chat more.

```go
kusto.Query(context.Background(), "<REMOVED>", kusto.NewStmt("ActivityLogs | project ResourceId | take 1"))
```

raw REQUEST payload for the above example. By default the following is set `"results_progressive_enabled":true`, since the query is of type `errors.OpQuery`. This is expected.

```text
POST /v2/rest/query HTTP/1.1
Host: <REMOVED>.kusto.windows.net
User-Agent: Go-http-client/1.1
Transfer-Encoding: chunked
Accept: application/json
Authorization: Bearer <REMOVED>
Content-Type: application/json; charset=utf-8
X-Ms-Client-Request-Id: KGC.execute;<REMOVED>
X-Ms-Client-Version: Kusto.Go.Client: 0.8.1
Accept-Encoding: gzip

de
{"db":"<REMOVED>","csl":"ActivityLogs | project ResourceId | take 1","properties":{"Options":{"results_progressive_enabled":true,"servertimeout":"00:03:59.9999963"},"Parameters":null,"Application":"","User":""}}

0
```

The RAW response payload is provided below, with some pieces removed. But it does show that we have `ROW` array populated. What's also interesting is that our Kusto cluster is reporting `"IsProgressive":false` even though the client set `results_progressive_enabled=true`. The server is also returning `TableProgress` frames in this non progressive response. I am not entirely sure if this is intentional, or a problem in Kusto server itself.  The end result is that the `kusto.RowIterator` object is empty and raises (EOF)

```text
HTTP/1.1 200 OK
Transfer-Encoding: chunked
Content-Type: application/json
Date: Wed, 26 Oct 2022 16:51:52 GMT
Server: Kestrel
Strict-Transport-Security: max-age=2592000; includeSubDomains
Vary: Accept-Encoding
X-Ms-Activity-Id: <REMOVED>
X-Ms-Client-Request-Id: KGC.execute;<REMOVED>

eff
[{"FrameType":"DataSetHeader","IsProgressive":false,"Version":"v2.0"},{"FrameType":"DataTable","TableId":0,"TableKind":"QueryProperties","TableName":"@ExtendedProperties","Columns":[{"ColumnName":"TableId","ColumnType":"int"},{"ColumnName":"Key","ColumnType":"string"},{"ColumnName":"Value","ColumnType":"dynamic"}],"Rows":[[1,"Visualization","{\"Visualization\":null,\"Title\":null,\"XColumn\":null,\"Series\":null,\"YColumns\":null,\"AnomalyColumns\":null,\"XTitle\":null,\"YTitle\":null,\"XAxis\":null,\"YAxis\":null,\"Legend\":null,\"YSplit\":null,\"Accumulate\":false,\"IsQuerySorted\":false,\"Kind\":null,\"Ymin\":\"NaN\",\"Ymax\":\"NaN\",\"Xmin\":null,\"Xmax\":null}"]]},{"FrameType":"TableHeader","TableId":1,"TableKind":"PrimaryResult","TableName":"PrimaryResult","Columns":[{"ColumnName":"ResourceId","ColumnType":"string"}]},{"FrameType":"TableFragment","TableFragmentType":"DataAppend","TableId":1,"Rows":[["<VALUE REMOVED>"]]},{"FrameType":"TableProgress","TableId":1,"TableProgress":0.0},{"FrameType":"TableCompletion","TableId":1,"RowCount":1},{"FrameType":"DataTable","TableId":2,"TableKind":"QueryCompletionInformation","TableName":"QueryCompletionInformation",
... REMOVED ...
{"FrameType":"DataSetCompletion","HasErrors":false,"Cancelled":false}]
0
```

## Work-around

I was able to fix this behaviour in two ways so far.

* As a test, I modified <https://github.com/Azure/azure-kusto-go/blob/master/kusto/kusto.go#L236-L253> to  always force the `progressiveSM{}` statemachine object. My reasoning was that the [Kusto V2 Spec](https://learn.microsoft.com/en-us/azure/data-explorer/kusto/api/rest/response2#datasetheader) hints that `TableProgress` is the result of a "progressive" frame. Even through our Kusto server is indicating the response payload is Frame V2 , but `"IsProgressive":false` though weirdly providing "progressive" frames in our response anyway. I wonder if our Kusto server is misconfigured, or some other state has drifted.
* Instead I built my query with `kusto.ResultsProgressiveDisable()` as such -> `kusto.Query(context.Background(), "<REMOVED>", kusto.NewStmt("ActivityLogs | project ResourceId | take 1"), kusto.ResultsProgressiveDisable())`. The hope here was to stop the server from responding with "progressive" FrameTypes (when it says it shouldn't). This also worked, and didn't require further hacking of the lib to support.

Is the response payload that includes `{"FrameType":"DataSetHeader","IsProgressive":false,"Version":"v2.0"}` coupled with `{"FrameType":"TableProgress","TableId":1,"TableProgress":0.0}` (progressive tables) an allowed response from a Kusto server?

* If so, there may be a bug in the nonProgressiveSM parsers.
* If not, why is my Kusto server doing this ;-)

**Comment by niontive** [comment]
Bumping this - I encountered the same issue.

**Comment by AsafMah** [comment]
Hey, this was an issue with the service.
It should be fixed now in all clusters, if it is still applicable, please comment.
