### ISSUE TITLE
API to set client version 

### ISSUE THREAD

**Issue by asaharn** [Azure/azure-kusto-go#138]
In current version of SDK a way to set client Version (similar to java sdk's [ConnectionStringBuilder.setClientVersionForTracing](https://github.com/Azure/azure-kusto-java/blob/master/data/src/main/java/com/microsoft/azure/kusto/data/auth/ConnectionStringBuilder.java#L163)) is missing
API can be implemented to set the client version so that it can be used for tracing and for connector/application specific stats which could be helpful for tracking clients' usage.

**Comment by AsafMah** [comment]
Added long ago :)
