### ISSUE TITLE
Using system assigned identity without azidext

### ISSUE THREAD

**Issue by roykn** [Azure/azure-kusto-go#155]
## Problem
I want to connect to kusto using system assigned identity. To do that I use the azidentity.NewDefaultAzureCredentials function from the **[azure-sdk-for-go](https://github.com/Azure/azure-sdk-for-go)** package to get a valid access token (cred). To build the needed authorizer (s. kusto.New(...)) I utilze azidext.NewTokenCredentialAdapter function from **[azidext](https://github.com/jongio/azidext)**

```go
cred, err := azidentity.NewDefaultAzureCredential(nil)
if err != nil {
 // ...
}

authorizer := &kusto.Authorization{
        Authorizer: azidext.NewTokenCredentialAdapter(cred, []string{endpoint}),
    }

client, err := kusto.New(endpoint, authorizer)
```

Because the code of the Azure Identity Extension (azidext) is not officially supported or intended for production use I want to get rid of it. How can I do that? How can I create an authorizer from a valid token or create a new kusto client with that token?

I've checked newer version descriptions without finding a hint that this will work or how it works with any of the newer versions.

## Versions used
github.com/Azure/azure-kusto-go v0.9.2
github.com/jongio/azidext/go/azidext v0.4.0

**Comment by AsafMah** [comment]
We have switched to a fully azidentity based authentication in 0.10.0.
Here is the method to create a connection string with a System assigned managed identity:
https://github.com/Azure/azure-kusto-go/blob/master/kusto/kcsb.go#L234

(Or right below it you can use the default azure credential, see if that gives you what you want when we updated our dependencies)

**Comment by roykn** [comment]
That's exactly what I was looking for. After update golang to 1.19 and azure-kusto-go 0.10.1 I get what I want. 
Thank you @AsafMah.
