### ISSUE TITLE
Latest version is incompatible with azblob v1.0.0

### ISSUE THREAD

**Issue by mx-psi** [Azure/azure-kusto-go#163]
Last week, there was a new release (v1.0.0) of [github.com/Azure/azure-sdk-for-go/sdk/storage/azblob](https://github.com/Azure/azure-sdk-for-go/releases/tag/sdk%2Fstorage%2Fazblob%2Fv1.0.0). This release introduces some breaking changes on the public API with respect to v0.6.1, the version [used by `azure-kusto-go`](https://github.com/Azure/azure-kusto-go/blob/7edcfd5ee188c0b7a82709e28abf68ad0ddf655e/go.mod#L10).

To allow using v1.0.0 of the `azblob` module on a Go module together with `azure-kusto-go`, we would need a new release that uses the new API.

**Comment by AsafMah** [comment]
We don't use anything that was broken from 0.6.1->1.0.0.
It seems that your repo is at our version 0.9.2,  which still used azblob 0.3.0, if you'll upgrade our package to 0.11.0, it should solve your errors.

**Comment by AsafMah** [comment]
@mx-psi did you look into my comment?
