### ISSUE TITLE
Add support to `ChainedTokenCredential`  (azidentity)

### ISSUE THREAD

**Issue by JorTurFer** [Azure/azure-kusto-go#177]
[This PR](https://github.com/Azure/azure-kusto-go/pull/105) replaces the authentication mechanism to use the new `azidentity` SDK and that's nice, but it only added some helper functions to the connection builder for using the authentications. There isn't any option to use a `ChainedTokenCredential` even though it's a supported `azcore.TokenCredential`. As it's a legit use case of azidentity SDK, kusto SDK should support it as well.

The use case:
In [KEDA](https://github.com/kedacore/keda) we have support for Kusto as a metric sources but we also support multiple types of authentications based on user given options. To handle this, [we have created our own `ChainedTokenCredential`](https://github.com/kedacore/keda/blob/main/pkg/scalers/azure/azure_azidentity_chain.go) based on our requirements and we have been using it with other upstreams like Azure Service Bus SDK. As `azidentity` SDK is unifying the authentication across all the azure SDKs, we'd like to use our `ChainedTokenCredential` in all of them, but this SDK doesn't support any way to provide this `ChainedTokenCredential` (or at least I haven't seen it, maybe I'm wrong 😄)

If you agree with this feature, I'm willing to contribute with it

**Comment by AsafMah** [comment]
Fixed in version 0.12.0 - added support for kcsb.WithTokenCredential(), you can now put in whatever credential you choose

**Comment by JorTurFer** [comment]
Thanks! I'll update our code asap ❤️
