### ISSUE TITLE
Question regarding 3rd party licenses

### ISSUE THREAD

**Issue by mntlty** [Azure/azure-kusto-go#194]
Hello!

The file https://github.com/Azure/azure-kusto-go/blob/master/THIRD_PARTY_LICENSES says

> Third party licenses may be located under each package in kusto/vendor/

but do not see a `/vendor` folder. 

Is this still applicable? It is causing confusion for automated license checks, which cannot identify that this project appears to only use the MIT license.

**Comment by elrayle** [comment]
Looks like the vendor folder was removed in Jan 2022 by PR #70.  There was some discussion about moving from vendor to go mod in PR #60.

**Comment by mntlty** [comment]
Go mod is currently in use 👍

**Comment by elrayle** [comment]
For clarity, the request is that the [THIRD_PARTY_LICENSES](https://github.com/Azure/azure-kusto-go/blob/master/THIRD_PARTY_LICENSES) file be removed.

**Comment by AsafMah** [comment]
Deleted the file
