### ISSUE TITLE
Escape kusto.ParamType default value of type string

### ISSUE THREAD

**Issue by nilsgstrabo** [Azure/azure-kusto-go#210]
Hi

Ref the `TODO` in [https://github.com/Azure/azure-kusto-go/blob/1161e23d078bdd354b3ea5b00f9066bf56e0f1a7/kusto/query_builder.go#L186](https://github.com/Azure/azure-kusto-go/blob/1161e23d078bdd354b3ea5b00f9066bf56e0f1a7/kusto/query_builder.go#L186)

Any plans on fixing this issue, e.g. by using the `kql.QuoteString` method which seems to be a perfect fit (?)

I tried to use the `QuoteString` method directly in a ParamType (`kusto.ParamType{Type: types.String, Default: kql.QuoteString(defaultValue)}`) but that failed since the code metioned above also encapsulates the string value in quotes.

It seems like a small fix, use QuoteString and remove the extra quotes:
```
return fmt.Sprintf(`%s:string = %s`, p.name, kql.QuoteString(v, false))
```
but I haven't studied the code thoroughly enough to understand if that would cause any issue.

**Comment by yogilad** [comment]
Released as part of version 0.15.0
