### ISSUE TITLE
Queries with `project-rename` are not working when `distinct` called before rename

### ISSUE THREAD

**Issue by sdehm** [Azure/azure-kusto-go#213]
It appears that calling `distinct` in a query followed by `project-rename` leads to results that do not have a renamed column. I modified the sample query from [the docs](https://learn.microsoft.com/en-us/azure/data-explorer/kusto/query/projectrenameoperator#examples) below:

```kql
print a='a', b='b', c='c' 
| distinct a 
|  project-rename new_a=a
```

The output of this query is

| a |
|-|
|a|

and not

| new_a |
|-|
|a|

as would be expected and as seen in Azure Data Explorer. The Python client also seems to execute the query correctly.

If the query is modified to rename before calling distinct it works as expected and renames the output column:

```kql
print a='a', b='b', c='c' 
|  project-rename new_a=a
| distinct new_a
```

The rename does seem to happen internally and in the original query if a `where` clause is added after renaming it respects the new name but still outputs the original name.

I'm not sure where in the source this is happening but will add more here if I find it.

**Comment by sdehm** [comment]
As an extra data point here I tried disabling progressive results with the `kusto.ResultsProgressiveDisable()` option and the renaming started to work. It seems like this has something to do with how the progressive results are processed or something like that?

**Comment by yogilad** [comment]
Progressive query is a bit complicated with regard to expected results. We're releasing a new version with progressive not being the default. 
That said, we'll check if the issue described above is a bug or a part of the protocol behavior.

**Comment by yogilad** [comment]
Issue will be fixed in the next rollout of Kusto Service
