### ISSUE TITLE
column decoding error - query return variance

### ISSUE THREAD

**Issue by pemj** [Azure/azure-kusto-go#23]
Ran into a strange issue earlier today. I'm not sure if the problem can be traced back to this library, or to kusto's API, so I figured I'd try getting in touch with both teams.

Two (slightly) different queries, upon examination through the kusto explorer, appear to return identical results. Specifically, they both return a single column named percentHealthy, and a single row storing a kusto Real. However, if we try to run those queries through azure-kusto-go, we get different results. The results of one of these queries will be converted successfully to a floating point value in Go, i.e. 94.343, whereas the result of the other query will return a blank floating point: 0.0000.  When we traced the code, we found that both query operations acquired the same value for this row, but that one query appeared to return an object with an incorrect column name, just a bunch of alphanumerics. 

The only difference in the queries is at the very end, where we project our final value.

The query that works with azure-kusto-go ends with this:
```
| extend percentHealthy=((1.0 * (total-(unhealthy)))/total)*100
| project percentHealthy
```
The query that doesn't work with azure-kusto-go ends like this:
```
| project percentHealthy=((1.0 * (total-(unhealthy)))/total)*100
```

Any idea where to look to dig into this?

**Comment by element-of-surprise** [comment]
Can you dump the columns in the successful case and an unsuccessful case and a sample output?

**Comment by element-of-surprise** [comment]
Also feel free to reach out to me on Teams.

**Comment by element-of-surprise** [comment]
Ping

**Comment by element-of-surprise** [comment]
Ping

**Comment by element-of-surprise** [comment]
Haven't gotten a response on this after 10 days, closing the bug.   If the bug is still an issue, please re-open and send the debug information requested above.
