### ISSUE TITLE
Create query for policy on cluster level

### ISSUE THREAD

**Issue by FakieHeelflip** [Azure/azure-kusto-go#244]
**Describe the bug**
Hi, first of all: I am not sure if this is a bug within this sdk. 

I want to build a kql query which will alter a policy on cluster level.

`.alter cluster policy request_classification SerializedPartialPolicy <| ClassificationFunctionBody`

The command will alter the request classification policy. https://learn.microsoft.com/en-us/azure/data-explorer/kusto/management/alter-cluster-policy-request-classification-command

The problem is, that the client.Query() func needs a database as a parameter but obviously there is no database to specify in the cluster policy. In older versions of this sdk within the client.Mgmt() func there have to be and nameIdentifier as well. 

Or is there always a DB (like a system db) in an ADX Cluster which I can specify?

Is there any chance to get this done? 

Best,
Christoph

**Comment by AsafMah** [comment]
Cluster-level commands simply ignore the database parameter, so you can pass an empty string or whatever you like for this type of command.

**Comment by AsafMah** [comment]
Closing, feel free to open with a comment.
