### ISSUE TITLE
Ingesting to Kusto Uploading String representation of key-value pair rather than just the value of key-value pair when ingesting from a stream

### ISSUE THREAD

**Issue by thomaspeiofficial** [Azure/azure-kusto-go#260]
**Describe the bug**

was attempting to use the kusto ingestion feature as follows:
 
```go
// dataSet in this case is a slice of a struct type as follows
type QueriedData struct {
// 	CloudFrom       string    `json:"cloudFrom,omitempty"`
// 	TimeStamp       time.Time `json:"timeStamp,omitempty"`
// 	Entity          string    `json:"entity,omitempty"`
// 	Stage           string    `json:"stage,omitempty"`
// 	StagerState     string    `json:"stagerState,omitempty"`
// 	VE              string    `json:"ve,omitempty"`
// 	OriginalVersion string    `json:"originalVersion,omitempty"`
// }
r, w := io.Pipe()
enc := json.NewEncoder(w)
go func() {
	defer w.Close()
	for _, data := range dataSet {
		if err := enc.Encode(data); err != nil {
			panic("add error handling")
		}
	}
}()
if _, err := in.FromReader(ctx, r); err != nil {
	panic("add error handling")
}
```
when I ingest to my kusto cluster, the output appears as the following:

![image](https://github.com/user-attachments/assets/165919a4-f5a6-4bda-9077-359127d4dbab)

In addition, when I print the contents of the input stream, I get the following output

`{"cloudFrom":"CloudFrom","timeStamp":"0001-01-01T00:00:00Z","entity":"Entity","stage":"StagerState","stagerState":"Stage","ve":"VE","originalVersion":"OriginalVersion"}`

**To Reproduce**

First set up a database table in kusto in a format similar to the struct in the bug description section.

Then in code, create a new struct array and create a new struct variable to add to an array of that struct type. Then replicate the IO.Pipe setup in the above example and add it to the pipe through the json.Encode function. Then ingest it to a database and check the contents

**Expected behavior**

I would expect a new row to appear in the table similar to the following:

![image](https://github.com/user-attachments/assets/165919a4-f5a6-4bda-9077-359127d4dbab)

except the output is just the value instead of the key-value pair (Ex: Entity instead of "entity": "Entity")

**Screenshots**

Bad Ingest example
![image](https://github.com/user-attachments/assets/165919a4-f5a6-4bda-9077-359127d4dbab)

**Setup (please complete the following information):**

go version go1.22.5 windows/386

**Desktop (please complete the following information):**
 - OS: Windows 11 Enterprise
 - Version: 23H2

**Additional context**

**Comment by AsafMah** [comment]
Your issue is that the default data format is CSV, if you want to ingest json data, you have to specify it explicitly:

`if _, err := in.FromReader(ctx, r, FileFormat(JSON)); err != nil {`


I saw you took the code from the sample, and it is also missing there - we will fix this.

**Comment by thomaspeiofficial** [comment]
> Your issue is that the default data format is CSV, if you want to ingest json data, you have to specify it explicitly:
> 
> `if _, err := in.FromReader(ctx, r, FileFormat(JSON)); err != nil {`
> 
> I saw you took the code from the sample, and it is also missing there - we will fix this.

Thanks for the response Asaf! Tried it out and looks like I'm getting empty rows in my table as follows:

![image](https://github.com/user-attachments/assets/f9bdc8e8-6793-448d-88c6-b007e612a08f)

For example here's what my code looks like after the update:

![image](https://github.com/user-attachments/assets/44a9bae7-ee65-46f0-a954-a6ec75e7d1eb)

**Comment by AsafMah** [comment]
1. How does your data look? If you just write `w` into a file, what's the format for each object and how does it separate between them?
2. Does doing it not in parallel - for example writing everything to a file first and only then reading and ingest - changes anything?

**Comment by thomaspeiofficial** [comment]
> 1. How does your data look? If you just write `w` into a file, what's the format for each object and how does it separate between them?
> 2. Does doing it not in parallel - for example writing everything to a file first and only then reading and ingest - changes anything?

1) Here's what I got when I wrote it out to a text file: 
![image](https://github.com/user-attachments/assets/575c3212-e2ef-4eea-91b5-d035ffd755e1)

and json

![image](https://github.com/user-attachments/assets/40c7a333-a383-4132-bbac-47bac937ce95)

2) 

Tried to write to a file and got an empty entry again when I tried to ingest the json file. When I ingested from the csv file I got a result similar to my original output in this incident as follows: 
![image](https://github.com/user-attachments/assets/9e588c1c-c60e-4563-b1ae-291ccb3dba6e)

**Comment by thomaspeiofficial** [comment]
Apologies, I realized what I got wrong. I had the json mapping lowercase the first letter; changed it to upper case like the fields in my kusto table and it worked. Again, sorry for the extra trouble.
