### ISSUE TITLE
How can I implement cursor based pagination?

### ISSUE THREAD

**Issue by goncalomarques** [Azure/azure-kusto-go#268]
Sorry for what seems to be a low effort post, but I'm not being able to see how I can get a query row cursor. I've searched both in the kusto ql docs, messed around on ADX UI and tried to do this using vs code autocomplete on my project but had no luck.

I want to do cursor based pagination where I would get sortable data from a row, and then start the next query there. 

The app I'm coding ingests time based data, but lots of the rows have the same value for time fields, so I can't use those. I was expecting kusto ql to provide me a cursor for each row.

I've search the kusto ql docs, and found something related to ExtendedProperties, but I'm not being able to use that in the golang code.

Thanks in advance

**Comment by AsafMah** [comment]
Depends on your use case, we have stored query results that support pagination:

https://learn.microsoft.com/en-us/kusto/query/stored-query-result-function?view=microsoft-fabric#pagination

And cursors based on ingestion time:

https://learn.microsoft.com/en-us/kusto/management/database-cursor?view=azure-data-explorer

**Comment by goncalomarques** [comment]
Thanks @AsafMah 
In the meantime I've started using the stored query results, as the ingestion time isn't guaranteed to be unique from what I read.
