### ISSUE TITLE
On certain query failures, we don't receive an error from the Go client

### ISSUE THREAD

**Issue by avivka** [Azure/azure-kusto-go#271]
### Bug Report

- azure-kusto-go : `sdk/resourcemanager/kusto/armkusto`
- go version: `1.23.0`
- SDK version: `v1.0.0-preview-5` (which seems to be the latest)

- What happened?
On certain query failures, we don't receive an error from the Go client (azure-kusto-go). For example, when running `(c *Client) Mgmt`, we get an error if the query fails due to a `429 Too Many Requests` response, but we don’t get one if it fails due to `UpdatePolicy_FailedDescendantTransaction`.
Do you know what could cause this?

- What did you expect or want to happen?
We expect that in the relevant case, `UpdatePolicy_FailedDescendantTransaction` will fail on `429 Too Many Requests` as well
- How can we reproduce it?
Run `(c *Client) Mgmt` on azure kusto for go's client

@yogilad @AsafMah

**Comment by yogilad** [comment]
@avivka , this is an ingestion failure status, not an error which commonly returns from Management calls?
Can you share specifically what command are you calling, and what's the code you use to do so?
If you have concrete examples, can you share the service name, timeframe of occurrence and client activity idea?

**Comment by yogilad** [comment]
Update: Issue seems to be with _.append_ command not returning an error when Update Policy fails the ingestion.
Issue routed to Engine team.
Item will be closed with details when resolution is provided.

**Comment by ohadbitt** [comment]
A possible solution would be to use  `.append async ` - on which you could perform `.show operations <guid>` command and see the error

**Comment by AsafMah** [comment]
Closing as this is not related to the sdk itself and a workaround was provided.

We will update if there are any further enhancements
