### ISSUE TITLE
azkustoingest: Export ingestion resources

### ISSUE THREAD

**Issue by noamcohen97** [Azure/azure-kusto-go#274]
**Is your feature request related to a problem? Please describe.**
I would like to access the storage container URI so that I could upload my a file, then call `FromFile()` with the blob URI

**Describe the solution you'd like**
Add exported `Ingestion` function that returns ingestion resources, such as storage container and queues

**Describe alternatives you've considered**
Management query `.get ingestion resources`

**Additional context**
I want to export the blob URI so that another micro-service could take care of the actual upload, and only then enqueue the message.

**Comment by AsafMah** [comment]
What use case do you have that calling `.get ingestion resources` doesn't fit your needs?

**Comment by noamcohen97** [comment]
> What use case do you have that calling `.get ingestion resources` doesn't fit your needs?

None, I could call it myself.
Just though it might be nicer to obtain it from the package since it's already there, cached, and ready to use.

**Comment by yogilad** [comment]
We don't normally expose internal client members. 
Making them public would render them harder to alter (breaking changes and all).

We are working on a new version of the _ingest_ SDK which will make it far simpler for users to separate the Upload phase from the ingest phase. Once it's out, it should be easy to leverage it to serve your needs.

Closing this for now. 
Feel free to reopen if you have further questions.
