### ISSUE TITLE
KHTTPError 520, System.IndexOutOfRangeException with private preview plugin

### ISSUE THREAD

**Issue by pemj** [Azure/azure-kusto-go#39]
So I've got something of a tricky problem. I'm getting an error that can only be reproduced with a combination of azure-kusto-go and a kusto plugin command that's in private preview.  If I run the query through kusto explorer, it works fine. And if I run most non-plugin queries through my azure-kusto-go client, it works fine. Even some queries with the plugin via the azure-kusto-go client work, just not all of them. 

The queries don't seem particularly complicated, they're basic heartbeat checks of the following form:

```
let mt = evaluate redacted_plugin_request('redacted_account_parameter', @'redacted_kqlm_parameter', ago(35m));
mt
| where Region in ("westus2")
| summarize percentHealthy=todouble(count())
```

When one of these queries breaks, it looks like this:

```
Op(OpQuery): Kind(KHTTPError): error from Kusto endpoint(520 ):
{
  "error": {
    "code": "Internal service error",
    "message": "Request aborted due to an internal service error.",
    "@type": "System.IndexOutOfRangeException",
    "@message": "Index was outside the bounds of the array.",
    "@context": {
      "timestamp": "2020-10-06T23:09:50.4300781Z",
      "serviceAlias": "redacted",
      "machineName": "KEngine000035",
      "processName": "Kusto.WinSvc.Svc",
      "processId": 4836,
      "threadId": 9492,
      "appDomainName": "Kusto.WinSvc.Svc.exe",
      "activityStack": "(Empty activity stack)"
    },
    "@permanent": false
  }
}
```

I raised the issue with the team who built the plugin, they asked me to talk to the kusto team. I raised the issue to the kusto team, and I have a suspicion that they're going to ask me to raise it with the team behind the client I'm using, so I figured I'd parallelize.

This kind of error look familiar at all? Any chance I'm, like, somehow using the client incorrectly in a way that can be easily fixed?

**Comment by pemj** [comment]
I've managed to produce, a single error from the kusto web explorer, but I can't repro it.  ( :
I shifted the timespan on that query down from ago(35m) to ago(1m), and it threw an error evaluating the plugin, `Message:An error occurred while sending the request.`, but every subsequent run, for that timespan or any other (down to ago(1s)), worked fine.  big shrug emoji

**Comment by zivcaspi** [comment]
Can you please provide a request ID for such a failure? Thx

**Comment by element-of-surprise** [comment]
This is a problem outside the SDK.  Support suggested that he prepend: set query_take_max_records=1000;
That apparently took care of the issue. 

If your interested Ziv, there is an ICM issue for this: https://portal.microsofticm.com/imp/v3/incidents/details/208378690/home

I'm going to close this issue as this doesn't look relevant to the Go SDK.  If there is some tweak needed Ziv, let me know.
