### ISSUE TITLE
http or https proxy support

### ISSUE THREAD

**Issue by frcai** [Azure/azure-kusto-go#46]
Looks like azure-kusto-go doesn't respect environment HTTP_PROXY (or HTTPS_PROXY) when ingest data to Kusto. We have some customers need uploading data to Kusto but client doesn't have direct access to internet and all outgoing traffic needs go through outbound proxy.

**Comment by yogilad** [comment]
Hi,

I'm not familiar with this environment and I don't see a reference to it in our Gold Standard SDK (C#).
This could be something the underlying http client libraries do on their own and Go does not, or it may not be supported there either.

You may be able to workaround the issue by setting a `netsh portproxy` rule.

**Comment by element-of-surprise** [comment]
It doesn't.  This is because we use our own http.Client instead of the default client.

The best way to support this is to allow customers to pass there own client.   We'd simply provide an option that pass a type that satisfies this interface:

```go
type HTTPClient interface {
	// Do sends an HTTP request and returns an HTTP response.
	Do(req *http.Request) (*http.Response, error)

	// CloseIdleConnections closes any idle connections in a "keep-alive" state.
	CloseIdleConnections()
}
```
They could pass whatever they want (different HTTP client implementations, the default one, whatever)...

**Comment by frcai** [comment]
Thanks Yochai and John. It'll be great to support the option John proposed. Do we have rough timeline to support this feature request?

**Comment by frcai** [comment]
Looking code today and found default http client was used, the issue is that wrong value  (with line break) configured on HTTP_PORXY (I'm using secrectRef in K8S cluster).  After removing the line break, data can be uploaded successfully through proxy. 

// NewPipeline creates a new goroutine-safe Pipeline object from the slice of Factory objects and the specified options.
func NewPipeline(factories []Factory, o Options) Pipeline {
	if o.HTTPSender == nil {
		o.HTTPSender = newDefaultHTTPClientFactory()
	}
	if o.Log.Log == nil {
		o.Log.Log = func(LogLevel, string) {} // No-op logger
	}
	return &pipeline{factories: factories, options: o}
}
