### ISSUE TITLE
Export SourceMessageCreationTime option (using FromFile)

### ISSUE THREAD

**Issue by talsheldon** [Azure/azure-kusto-go#53]
I want to set `SourceMessageCreationTime` option in my ingestion process that using (in this case) `FromFile`.

Seems like this option exists, but not exported (correct me if I'm wrong).

Why?
I want to override creationTime, the data shard's creation to make sure retention and caching policies are applied (to what I specify in the creationTime).

Using `go1.16` and `github.com/Azure/azure-kusto-go v0.3.2`

**Comment by element-of-surprise** [comment]
Talsheldon... 

I'll see if anyone happens to remember, but the likely culprits are:
- We just missed adding the exposure option
- We skipped exposing it to avoid the clutter of unused options and no one asked for them

Kusto has a lot of options that I didn't expose in the Go packages.  With very few exceptions, no one asks for them.  They end up being clutter that isn't needed.  And there are some more technical reasons that aren't worth going into.

If you need the option, we can look at exposing it via an Ingestion option.

**Comment by yogilad** [comment]
The source message creation time does not affect the retention policy.
It is used to monitor the ingestion pipeline progress.

[Kusto retention policy controls how data is removed - Azure Data Explorer | Microsoft Docs](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/management/retentionpolicy#the-policy-object)

SoftDeletePeriod:
•	Time span for which it's guaranteed that the data is kept available to query. **_The period is measured starting from the time the data was ingested._**
•	Defaults to 100 years.
•	When altering the soft-delete period of a table or database, the new value applies to both existing and new data.

**Comment by yogilad** [comment]
Created a PR to set creationTime ingestion property (different from SourceMessageCreationTime).
This should allow use to set the date & time the retention policy is considered against
