### ISSUE TITLE
Errors occurred while resolving remote entities

### ISSUE THREAD

**Issue by w1ndy** [Azure/azure-kusto-go#76]
It looks like the progressive query option, which is on by default, can't be used in cross-cluster queries. These queries will fail with a bad request error, saying:

> Errors occurred while resolving remote entities. Failed to resolve entityNameOrPattern='xxx' in one or more scopes: ($Cluster='https://xxx.kusto.windows.net/', Database='xxx')

Putting this in docs may save hours of debugging...

**Comment by yogilad** [comment]
@w1ndy , can you share an example query?

**Comment by w1ndy** [comment]
> @w1ndy , can you share an example query?

I can't seem to replicate this bug with simple queries, might be related to other things since I was doing a rather complex query... Anyway I'll close this issue for now, and I'll get back to you if I managed to reproduce the issue. Thanks!

**Comment by AsafMah** [comment]
I did manage to replicate it.
Currently it seems like a bug in the engine, I've forwarded it to the team and will keep you updated.
I will keep this close since it's not related to the sdk.

As a workaround, it seems that running the query non-progressively sometimes causes the progressive query to work after, I assume due to caching.

**Comment by sodacorsair** [comment]
> I did manage to replicate it. Currently it seems like a bug in the engine, I've forwarded it to the team and will keep you updated. I will keep this close since it's not related to the sdk.
> 
> As a workaround, it seems that running the query non-progressively sometimes causes the progressive query to work after, I assume due to caching.

Can you explain what is progressive query and non-progressive one? Recently I encountered the same issue.
