### ISSUE TITLE
Enable access to "non-primary" tables in the response, mainly for cursor feature

### ISSUE THREAD

**Issue by liranms** [Azure/azure-kusto-go#85]
Provide ability to access the response that contains other table such as `@ExtendedProperties`, and `QueryResourceConsumption`
this is very important for using the kusto [database cursor feature ](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/management/databasecursor) which emits the Cursor property on the `@ExtendedProperties` table
Another interesting aspect is getting the performance metadata on the QueryResourceConsumption for every executed query.
I saw that there was an unused, unexported function named `getNonPrimary` which hints that you were going to export this feature, currently I just forked and exported it.

**Comment by liranms** [comment]
@AsafMah is there a plan to expose this?

**Comment by AsafMah** [comment]
#90 does it, it would soon be completed and will be released in the next version.
